//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiscStore.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARTISTS_GENRES_LINKS
    {
        public int LinkID { get; set; }
        public int GenreID { get; set; }
        public int ArtistID { get; set; }
    
        public virtual Artists Artists { get; set; }
        public virtual Genres Genres { get; set; }
    }
}
